[package]
name = "zicklag/ulid_cli"
version = "0.1.1"
description = "Dead simple CLI for generating ULID identifiers."
wasmer-extra-flags = "--enable-bulk-memory"

[dependencies]
"zicklag/ulid_cli" = "0.1.0"

[[module]]
name = "ulid"
source = "target/wasm32-wasi/release/ulid_cli.wasm"
abi = "wasi"

[[command]]
name = "ulid"
module = "ulid"
